name: Terraform Apply

# Section 1: Trigger on push to main, manual dispatch, and scheduled at 1 AM UTC daily
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 1 * * *'  # 1 AM UTC daily

env:
  TERRAFORM_DIRECTORY: './'  # Specify the Terraform working directory if it's the root; change if needed

permissions:
  id-token: write
  contents: read

jobs:

  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      # Section 2: Google Authentication using Workload Identity Federation (WIF)
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.GCP_SERVICE_ACCOUNT }}"  # Set this secret in GitHub with the service account email

      # Initialize Terraform
      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ${{ env.TERRAFORM_DIRECTORY }}

      # Section 3: Terraform Checks - Formatting, Validation, and Plan
      - name: Terraform format and validate
        id: checks
        run: |
          terraform fmt -check  # Check for formatting issues
          terraform validate     # Validate the syntax and configuration
        working-directory: ${{ env.TERRAFORM_DIRECTORY }}

      - name: Terraform plan
        id: plan
        run: terraform plan -out=tfplan  # Create an execution plan
        working-directory: ${{ env.TERRAFORM_DIRECTORY }}

      # Optional: Apply changes only if manually approved or for certain workflows
      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'  # Only applies automatically if manually triggered
        run: terraform apply "tfplan"
        working-directory: ${{ env.TERRAFORM_DIRECTORY }}
        shell: bash
